# ----------------------------------------
# Service: api-cms
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: api-cms
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: api-cms
    app.kubernetes.io/tier: api
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/service: api-cms
    app.kubernetes.io/tier: api  
---
# ----------------------------------------
# Deployment: api-cms
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-cms
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: api-cms
    app.kubernetes.io/tier: api
spec:
  replicas: {{ .Values.apiCms.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/service: api-cms
      app.kubernetes.io/tier: api
  template:
    metadata:
      labels:
        app.kubernetes.io/service: api-cms
        app.kubernetes.io/tier: api
    spec:
      containers:
        - name: web
          image: "gcr.io/beamaustralia/api-cms:{{ .Values.version }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-secrets          
          ports:
              - containerPort: 80              
          resources:
            requests:
              cpu: 50m
              memory: {{ .Values.apiCms.memory }}
