# ----------------------------------------
# Service
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/service: gateway
    app.kubernetes.io/tier: network
spec:
  type: LoadBalancer  
  loadBalancerIP: {{ .Values.gateway.ip }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443  
  selector:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/service: gateway
---
# ----------------------------------------
# Deployment
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/service: gateway
    app.kubernetes.io/tier: network
spec:
  replicas: {{ .Values.gateway.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "beam.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/service: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "beam.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/service: gateway
    spec:
      containers:
        - name: web
          image: "gcr.io/beam-au/gateway:{{ .Values.version }}"
          imagePullPolicy: Always
          env:
            - name: GCE_PROJECT
              value: "beam-au"
            - name: GCE_SERVICE_ACCOUNT_FILE
              value: '{"type":"service_account","project_id":"beam-au","private_key_id":"0877d22784ffa412382a6f268888e06bfe5b40f0","private_key":"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDI7X2P+FxstgC7\niX2V/E1jpxai4BN4uzTEzFBVXg3n9BGZM/vyhCD3orEW4qb/9ZcCvZ8124TVJ3ma\nD7/RxjXcd55YE5P2H6ABgsnyLdZui5Nv2AdR5nUabl+9AjybZErU4d74TK728pPp\n4lyCVqXRRMIebE/Ic3uU9M+SOtE/Km5LRUwr7kOPkHtbNGe1y+HNR2AcXBNUgpV9\nUXS+MG4EXxA9PIJaGa2jdrVDCB+VNdgCxQZh4ZQBNw+v8gA6hRkjpn7+j26jt9If\nKa6jEqeTbf6ZVZLo5Uw4pJG/ENgoueyOsSXQRYGAPvGm0/JXM6vkQTk7KX5pXsCZ\nEJxRBaQFAgMBAAECggEAKixc/0fCQIgoGbTnYQCazsiesfOl6qCimA8Jao2qDg5W\n1kkIwDO3BrtFf9f1dQKbnnXmEcQgeqwFNE7LdJCts/eAixya4R1stHx6/kPcPwo5\nWU+m46wjVreljTLHvVb89Pdu2T+hNtCeNshuIeZlegn8U63oxhplLVQAMIF7c44J\nXbstEiD4whThUVr0lRw5a2Xaz9t+t8Su3w7WzkCqJJmmN9ISQj/uX8iqcIZu6rbi\ntaSuMhu7O7JYEUqOo2zz9/SFwb9dJSvpcx2WsXTFi6a6qYGtz9kgXFUl+pOQftNQ\ncbpbovafAD++E0tTSeXJEux5mTM41mS8IUwz/jtW6QKBgQDr6SgODdpPduKVsG0a\ng3k1oQm9kHQRP27ufFpmbIN2BQFYs4VfxsQRLvz6BuKr2O1bmEKAucIJ0/oj4b3z\njxhDpJv5laxzkoib5aIbgM39WKfOI7wCbSZIRlAZn1GoIAmDZdROqZqbeyFvV94/\n+U7+qEaOmECr1C7mHAtOlGvzvQKBgQDaCbRp+MzvBPkTYkINYCn4lukUUAWIOdDH\nJ0VJi4DdMZEc6fx51p8WXPEhrU8niE7XxiKzPM7E17n1n+X4ivUkpeLFIG8iC8NZ\nLK7cNh8b8MiOaNrNR0VH6ZxejvY2bIv3cwT8T15NrXvSC0Qqe8L26LJcLlP1EgFq\nWc27dJ5R6QKBgQCUcj+xMEhaTo3f8YeF8osYEwCFF1vh6o+MZBWic8/5OMcTIMvh\na7q+sVmgnyqNRlB9nX7jb4BJHOk/IPKdS0LSdcdsMyG0C9YIe2QZeGCmdd4J2fSZ\ndkNroUsQBG+mopo5457H7POLuNxeKuWATgnGNu9HFUlElpz4UVdQGBch5QKBgQCY\nX7/dbyqIv4jxqvFON64dNBmfQG0dTopBI4igZQWhj0pCUqNG4l47WqiJSHzQu8md\nsbH+YLh/h+NFbIFiuHmpKuTXrlr8CAx0/W0WKByFgjgmjdCbNPuNzgyhaHdYgXMv\ncwpA6ZaV4m9t0sHIjsUpmGVNVnMGCZdDo47LOiyKQQKBgD4XA3MJbDouigDv5+3R\nwVWVG1qKIZwAf43jxmsMLz8ITsH/EWmSJGrYj37EnEM0oKgxE2sVNyC/ab9N46Vn\nE7st/wj2AFNVWSi8JmOKmNhJp7XjU0IX37vRc6QR0GhezSimWFg+C8fImUvNzbMg\n54V34su6rJW2Qsdd3h2ejAnC\n-----END PRIVATE KEY-----\n","client_email": "robots@beam-au.iam.gserviceaccount.com","client_id": "102567742163067924677","auth_uri": "https://accounts.google.com/o/oauth2/auth","token_uri": "https://oauth2.googleapis.com/token","auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/robots%40beam-au.iam.gserviceaccount.com"}'
          ports:
              - containerPort: 80
              - containerPort: 443
          resources:
            requests:
              cpu: 50m
              memory: {{ .Values.gateway.memory }}
