# ----------------------------------------
# Service
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: service-redis
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: redis
    app.kubernetes.io/tier: service
spec:
  ports:
    - port: 6379
      targetPort: 6379 
  selector:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: redis
    app.kubernetes.io/tier: service
---
# ----------------------------------------
# Deployment
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-redis
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: redis
    app.kubernetes.io/tier: service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "beam.name" . }}
      app.kubernetes.io/version: {{ .Values.version }}
      app.kubernetes.io/service: redis
      app.kubernetes.io/tier: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "beam.name" . }}
        app.kubernetes.io/version: {{ .Values.version }}
        app.kubernetes.io/service: redis
        app.kubernetes.io/tier: service
    spec:
      containers:
        - name: web
          image: "redis:5-alpine"
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi