# ----------------------------------------
# Service
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: service-uploads
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: uploads
    app.kubernetes.io/tier: service
spec:
  ports:
    - port: 80
      targetPort: 80 
  selector:
      app.kubernetes.io/service: uploads
      app.kubernetes.io/tier: service
---
# ----------------------------------------
# Deployment
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-uploads
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: uploads
    app.kubernetes.io/tier: service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/service: uploads
      app.kubernetes.io/tier: service
  template:
    metadata:
      labels:
        app.kubernetes.io/service: uploads
        app.kubernetes.io/tier: service
    spec:
      containers:
        - name: web
          image: "gcr.io/beam-au/tusd:0.6.0"
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi