# ----------------------------------------
# Service
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: web-staff
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: web-staff
    app.kubernetes.io/tier: web
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/service: web-staff
    app.kubernetes.io/tier: web
---
# ----------------------------------------
# Deployment
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-staff
  labels:
    app.kubernetes.io/name: {{ include "beam.name" . }}
    app.kubernetes.io/version: {{ .Values.version }}
    app.kubernetes.io/service: web-staff
    app.kubernetes.io/tier: web
spec:
  replicas: {{ .Values.webStaff.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/service: web-staff
      app.kubernetes.io/tier: web
  template:
    metadata:
      labels:
        app.kubernetes.io/service: web-staff
        app.kubernetes.io/tier: web
    spec:
      containers:
        - name: web
          image: "gcr.io/beamaustralia/web-staff:{{ .Values.version }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: service-configs
            - secretRef:
                name: service-secrets          
          ports:
              - containerPort: 3000
          resources:
            requests:
              cpu: 25m
              memory: {{ .Values.webStaff.memory }}
